// ----------------------------------------------------------------------------------
// Copyright (c) The Standard Organization: A coalition of the Good-Hearted Engineers
// ----------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace STX.EFCore.Client.Clients
{
    /// <summary>
    /// Provides EF Core data operations for inserting, querying, updating, deleting,
    /// and bulk processing entities against a <see cref="Microsoft.EntityFrameworkCore.DbContext"/>.
    /// </summary>
    public interface IEFCoreClient
    {
        /// <summary>
        /// Inserts a single entity of type <typeparamref name="T"/> into the data store.
        /// </summary>
        /// <typeparam name="T">The entity type to insert. Must be a reference type.</typeparam>
        /// <param name="object">The entity instance to insert. Must not be <see langword="null"/>.</param>
        /// <param name="cancellationToken">
        /// A token that can be used to request cancellation of the operation.
        /// Defaults to <see cref="CancellationToken.None"/>.
        /// </param>
        /// <returns>
        /// A <see cref="ValueTask{T}"/> that resolves to the inserted entity, including any
        /// values generated by the database (e.g. auto-generated keys or computed columns).
        /// </returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="object"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="DbUpdateException">
        /// Thrown when the database rejects the insert — for example due to a unique constraint
        /// violation, a check constraint failure, or a <c>NOT NULL</c> column receiving a null value.
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// Thrown when the operation is cancelled via <paramref name="cancellationToken"/>.
        /// </exception>
        ValueTask<T> InsertAsync<T>(T @object, CancellationToken cancellationToken = default)
            where T : class;

        /// <summary>
        /// Retrieves all entities of type <typeparamref name="T"/> from the data store as a queryable.
        /// </summary>
        /// <typeparam name="T">The entity type to retrieve. Must be a reference type.</typeparam>
        /// <param name="cancellationToken">
        /// A token that can be used to request cancellation of the operation.
        /// Defaults to <see cref="CancellationToken.None"/>.
        /// </param>
        /// <returns>
        /// A <see cref="ValueTask{T}"/> that resolves to an <see cref="IQueryable{T}"/> over
        /// all entities of the specified type. Further LINQ operators can be composed on the result
        /// before it is executed against the database.
        /// </returns>
        /// <exception cref="InvalidOperationException">
        /// Thrown when the entity type <typeparamref name="T"/> is not registered in the
        /// <see cref="DbContext"/> model.
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// Thrown when the operation is cancelled via <paramref name="cancellationToken"/>.
        /// </exception>
        ValueTask<IQueryable<T>> SelectAllAsync<T>(CancellationToken cancellationToken = default)
            where T : class;

        /// <summary>
        /// Retrieves a single entity of type <typeparamref name="T"/> by its primary key(s).
        /// </summary>
        /// <typeparam name="T">The entity type to retrieve. Must be a reference type.</typeparam>
        /// <param name="objectIds">
        /// An array of primary key values that uniquely identify the entity.
        /// The order and count must match the entity's primary key definition.
        /// Must not be <see langword="null"/>.
        /// </param>
        /// <param name="cancellationToken">
        /// A token that can be used to request cancellation of the operation.
        /// Defaults to <see cref="CancellationToken.None"/>.
        /// </param>
        /// <returns>
        /// A <see cref="ValueTask{T}"/> that resolves to the matching entity, or
        /// <see langword="null"/> if no entity with the given key(s) exists.
        /// </returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="objectIds"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="InvalidOperationException">
        /// Thrown when the entity type <typeparamref name="T"/> is not registered in the
        /// <see cref="DbContext"/> model, or when the number of supplied key values does not
        /// match the entity's primary key definition.
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// Thrown when the operation is cancelled via <paramref name="cancellationToken"/>.
        /// </exception>
        ValueTask<T> SelectAsync<T>(object[] objectIds, CancellationToken cancellationToken = default)
            where T : class;

        /// <summary>
        /// Updates a single existing entity of type <typeparamref name="T"/> in the data store.
        /// </summary>
        /// <typeparam name="T">The entity type to update. Must be a reference type.</typeparam>
        /// <param name="object">The entity instance with updated values. Must not be <see langword="null"/>.</param>
        /// <param name="cancellationToken">
        /// A token that can be used to request cancellation of the operation.
        /// Defaults to <see cref="CancellationToken.None"/>.
        /// </param>
        /// <returns>
        /// A <see cref="ValueTask{T}"/> that resolves to the updated entity as it exists
        /// in the data store after the operation completes.
        /// </returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="object"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="DbUpdateConcurrencyException">
        /// Thrown when a concurrency conflict is detected — i.e. the row was modified or deleted
        /// by another process between the time it was read and the time the update was saved.
        /// </exception>
        /// <exception cref="DbUpdateException">
        /// Thrown when the database rejects the update — for example due to a unique constraint
        /// violation, a check constraint failure, or a foreign key constraint violation.
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// Thrown when the operation is cancelled via <paramref name="cancellationToken"/>.
        /// </exception>
        ValueTask<T> UpdateAsync<T>(T @object, CancellationToken cancellationToken = default)
            where T : class;

        /// <summary>
        /// Deletes a single entity of type <typeparamref name="T"/> from the data store.
        /// </summary>
        /// <typeparam name="T">The entity type to delete. Must be a reference type.</typeparam>
        /// <param name="object">The entity instance to delete. Must not be <see langword="null"/>.</param>
        /// <param name="cancellationToken">
        /// A token that can be used to request cancellation of the operation.
        /// Defaults to <see cref="CancellationToken.None"/>.
        /// </param>
        /// <returns>
        /// A <see cref="ValueTask{T}"/> that resolves to the deleted entity as it was
        /// before removal from the data store.
        /// </returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="object"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="DbUpdateException">
        /// Thrown when the database rejects the delete — most commonly because another entity
        /// holds a foreign key reference to this record (referential integrity violation).
        /// </exception>
        /// <exception cref="DbUpdateConcurrencyException">
        /// Thrown when a concurrency conflict is detected — i.e. the row was already deleted
        /// by another process before this operation could remove it.
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// Thrown when the operation is cancelled via <paramref name="cancellationToken"/>.
        /// </exception>
        ValueTask<T> DeleteAsync<T>(T @object, CancellationToken cancellationToken = default)
            where T : class;

        /// <summary>
        /// Inserts a collection of entities of type <typeparamref name="T"/> into the data store
        /// in a single batch operation.
        /// </summary>
        /// <typeparam name="T">The entity type to insert. Must be a reference type.</typeparam>
        /// <param name="objects">
        /// The collection of entity instances to insert. Must not be <see langword="null"/>.
        /// </param>
        /// <param name="useTransaction">
        /// When <see langword="true"/> (the default), the entire batch is wrapped in a database
        /// transaction that is rolled back automatically if any error occurs.
        /// Set to <see langword="false"/> to skip transaction management.
        /// </param>
        /// <param name="cancellationToken">
        /// A token that can be used to request cancellation of the operation.
        /// Defaults to <see cref="CancellationToken.None"/>.
        /// </param>
        /// <returns>A <see cref="ValueTask"/> that represents the asynchronous bulk insert operation.</returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="objects"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="DbUpdateException">
        /// Thrown when the database rejects one or more rows in the batch — for example due to
        /// a unique constraint violation, a check constraint failure, or a <c>NOT NULL</c> column
        /// receiving a null value.
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// Thrown when the operation is cancelled via <paramref name="cancellationToken"/>.
        /// </exception>
        ValueTask BulkInsertAsync<T>(
            IEnumerable<T> objects,
            bool useTransaction = true,
            CancellationToken cancellationToken = default)
            where T : class;

        /// <summary>
        /// Retrieves a collection of entities of type <typeparamref name="T"/> from the data store
        /// whose primary keys match those of the supplied objects.
        /// </summary>
        /// <typeparam name="T">The entity type to read. Must be a reference type.</typeparam>
        /// <param name="objects">
        /// A collection of entity instances whose primary key values are used as lookup criteria.
        /// Must not be <see langword="null"/>.
        /// </param>
        /// <param name="cancellationToken">
        /// A token that can be used to request cancellation of the operation.
        /// Defaults to <see cref="CancellationToken.None"/>.
        /// </param>
        /// <returns>
        /// A <see cref="ValueTask{T}"/> that resolves to an <see cref="IEnumerable{T}"/> containing
        /// the entities from the data store that matched the supplied keys.
        /// Entities whose keys were not found in the store are omitted from the result.
        /// </returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="objects"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="InvalidOperationException">
        /// Thrown when the entity type <typeparamref name="T"/> has no primary key defined
        /// in the <see cref="DbContext"/> model.
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// Thrown when the operation is cancelled via <paramref name="cancellationToken"/>.
        /// </exception>
        ValueTask<IEnumerable<T>> BulkReadAsync<T>(
            IEnumerable<T> objects,
            CancellationToken cancellationToken = default)
            where T : class;

        /// <summary>
        /// Updates a collection of existing entities of type <typeparamref name="T"/> in the data store
        /// in a single batch operation.
        /// </summary>
        /// <typeparam name="T">The entity type to update. Must be a reference type.</typeparam>
        /// <param name="objects">
        /// The collection of entity instances with updated values. Must not be <see langword="null"/>.
        /// </param>
        /// <param name="useTransaction">
        /// When <see langword="true"/> (the default), the entire batch is wrapped in a database
        /// transaction that is rolled back automatically if any error occurs.
        /// Set to <see langword="false"/> to skip transaction management.
        /// </param>
        /// <param name="cancellationToken">
        /// A token that can be used to request cancellation of the operation.
        /// Defaults to <see cref="CancellationToken.None"/>.
        /// </param>
        /// <returns>A <see cref="ValueTask"/> that represents the asynchronous bulk update operation.</returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="objects"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="DbUpdateConcurrencyException">
        /// Thrown when a concurrency conflict is detected for one or more entities in the batch.
        /// </exception>
        /// <exception cref="DbUpdateException">
        /// Thrown when the database rejects one or more rows in the batch — for example due to
        /// a unique constraint violation, a check constraint failure, or a foreign key constraint violation.
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// Thrown when the operation is cancelled via <paramref name="cancellationToken"/>.
        /// </exception>
        ValueTask BulkUpdateAsync<T>(
            IEnumerable<T> objects,
            bool useTransaction = true,
            CancellationToken cancellationToken = default)
            where T : class;

        /// <summary>
        /// Deletes a collection of entities of type <typeparamref name="T"/> from the data store
        /// in a single batch operation.
        /// </summary>
        /// <typeparam name="T">The entity type to delete. Must be a reference type.</typeparam>
        /// <param name="objects">
        /// The collection of entity instances to delete. Must not be <see langword="null"/>.
        /// </param>
        /// <param name="useTransaction">
        /// When <see langword="true"/> (the default), the entire batch is wrapped in a database
        /// transaction that is rolled back automatically if any error occurs.
        /// Set to <see langword="false"/> to skip transaction management.
        /// </param>
        /// <param name="cancellationToken">
        /// A token that can be used to request cancellation of the operation.
        /// Defaults to <see cref="CancellationToken.None"/>.
        /// </param>
        /// <returns>A <see cref="ValueTask"/> that represents the asynchronous bulk delete operation.</returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="objects"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="DbUpdateException">
        /// Thrown when the database rejects the deletion of one or more rows — most commonly because
        /// another entity holds a foreign key reference to a record being deleted
        /// (referential integrity violation).
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// Thrown when the operation is cancelled via <paramref name="cancellationToken"/>.
        /// </exception>
        ValueTask BulkDeleteAsync<T>(
            IEnumerable<T> objects,
            bool useTransaction = true,
            CancellationToken cancellationToken = default)
            where T : class;

        /// <summary>
        /// Inserts new entities and updates existing entities of type <typeparamref name="T"/> in the
        /// data store in a single batch operation. Existence is determined by comparing primary key values:
        /// entities whose keys are already present are updated; all others are inserted.
        /// </summary>
        /// <typeparam name="T">The entity type to upsert. Must be a reference type.</typeparam>
        /// <param name="objects">
        /// The collection of entity instances to insert or update. Must not be <see langword="null"/>.
        /// </param>
        /// <param name="useTransaction">
        /// When <see langword="true"/> (the default), the insert and update phases are wrapped together
        /// in a single database transaction that is rolled back automatically if any error occurs.
        /// Set to <see langword="false"/> to skip transaction management.
        /// </param>
        /// <param name="cancellationToken">
        /// A token that can be used to request cancellation of the operation.
        /// Defaults to <see cref="CancellationToken.None"/>.
        /// </param>
        /// <returns>A <see cref="ValueTask"/> that represents the asynchronous bulk upsert operation.</returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="objects"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="InvalidOperationException">
        /// Thrown when the entity type <typeparamref name="T"/> has no primary key defined
        /// in the <see cref="DbContext"/> model.
        /// </exception>
        /// <exception cref="DbUpdateException">
        /// Thrown when the database rejects one or more rows during the insert or update phase —
        /// for example due to a unique constraint violation, a check constraint failure, or a
        /// foreign key constraint violation.
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// Thrown when the operation is cancelled via <paramref name="cancellationToken"/>.
        /// </exception>
        ValueTask BulkUpsertAsync<T>(
            IEnumerable<T> objects,
            bool useTransaction = true,
            CancellationToken cancellationToken = default)
            where T : class;

        /// <summary>
        /// Determines whether an entity of type <typeparamref name="T"/> with the specified
        /// primary key(s) exists in the data store.
        /// </summary>
        /// <typeparam name="T">The entity type to check. Must be a reference type.</typeparam>
        /// <param name="objectIds">
        /// An array of primary key values that uniquely identify the entity.
        /// The order and count must match the entity's primary key definition.
        /// Must not be <see langword="null"/>.
        /// </param>
        /// <param name="cancellationToken">
        /// A token that can be used to request cancellation of the operation.
        /// Defaults to <see cref="CancellationToken.None"/>.
        /// </param>
        /// <returns>
        /// A <see cref="ValueTask{T}"/> that resolves to <see langword="true"/> if an entity with
        /// the given key(s) exists in the data store; otherwise <see langword="false"/>.
        /// </returns>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="objectIds"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="InvalidOperationException">
        /// Thrown when the number of supplied key values does not match the entity's
        /// primary key definition.
        /// </exception>
        /// <exception cref="OperationCanceledException">
        /// Thrown when the operation is cancelled via <paramref name="cancellationToken"/>.
        /// </exception>
        ValueTask<bool> ExistsAsync<T>(object[] objectIds, CancellationToken cancellationToken = default)
            where T : class;
    }
}
